# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('id',)},
        ),
    ]
